name: firebase_cloud_messaging_interop
description: A dart plugin to use the Firebase Cloud Messaging Api (JS). You can retrieve the user's FCM token, delete it, access the notification data, ...

version: 1.2.0
repository: https://github.com/GaspardMerten/Firebase-Cloud-Messaging-Interop
homepage: https://github.com/GaspardMerten/Firebase-Cloud-Messaging-Interop
author: Gaspard Merten <gaspard.mp.work@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  js: ^0.6.0
