name: firebase_cloud_messaging_interop
description: A dart plugin allowing you to retrieve the firebase token of the client and to send push notification (via firebase).

# version: 1.0.0
# homepage: https://www.example.com
# author: Gaspard Merten <gaspard.mp.work@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  test: ^1.0.0
